### ISSUE TITLE
PerfTimer with trio.to_thread.run_sync

### ISSUE THREAD

**Issue by mozesa** [belm0/perf-timer#2]
Hello **John**,

I bumped into the issue below.

```python
import trio
from perf_timer import PerfTimer


def dummy():
    pass


@PerfTimer("handle_events_01")
async def handle_events() -> None:
    # await trio.to_thread.run_sync(dummy)
    await trio.sleep(1)


async def async_main():
    with trio.move_on_after(10.0):
        while True:
            await handle_events()
            await trio.sleep(0)


trio.run(async_main)
```

`PerfTimer` (`TrioPerfTimer`) reports me that `timer "handle_events_01": average 1.01 s, max 1.02 s in 9 runs` but when I uncomment this line `await trio.to_thread.run_sync(dummy)` it no longer shows anything at the end of program.

Do I miss something?

Thanks for your help in advance.

Btw the lib is really helpful. 👍

**Comment by belm0** [comment]
Thank you for reporting.

First, note that `PerfTimer` isn't really intended for async functions because it will count periods of trio.sleep(), waiting for I/O, waiting for other tasks, etc.  Use `TrioPerfTimer` instead.

But your bug regarding no output when using `run_sync()` is valid, and it's a case of #1.   Perhaps there is a bug in Trio causing resources to not be freed.  I'll file a Trio bug.

**Comment by belm0** [comment]
Filed https://github.com/python-trio/trio/issues/1638

**Comment by mozesa** [comment]
# https://github.com/python-trio/trio/issues/1638
PR has been merged successfully so I think we can close it now.
Thanks for your kind and prompt help.
